package com.epam.jwd.hotel_booking.command;

public enum Vars {
    NOW_DATE("nowDate"),
    LOGIN("login"),
    RELATED_LOGIN_FOR_SHOW_ORDERS("related_login_for_show_orders"),
    PASSWORD("password"),
    LOCALE("locale"),
    RESOURCE_BUNDLE("rb"),
    ROLE("role"),
    CURRENT_PAGE("current_page"),
    LOGIN_LIST("login_list"),
    LOGIN_ID_FOR_SET_ROLE("login_id_for_set_role"),
    LOGIN_FOR_SHOW_ORDERS("login_for_show_orders"),
    LOGIN_FOR_SHOW_CLIENTS("login_for_show_clients"),
    NAME_INCLUDE("name_include"),
    SNAME_INCLUDE("sname_include"),
    EMAIL_INCLUDE("email_include"),
    PHONE_INCLUDE("phone_include"),
    BDAY_FROM("bday_from"),
    BDAY_TO("bday_to"),
    ADDRESS_INCLUDE("adress_include"),
    COUNTRIES("country_list"),
    LANGPACKAGE("langpackage"),
    NAME("name"),
    SNAME("sname"),
    EMAIL("email"),
    PHONE("phone"),
    BDAY("bday"),
    SEX("sex"),
    COUNTRY("country"),
    ADDRESS("address"),
    CLIENT_LIST("client_list"),
    ORDER_LIST("order_list"),
    ID_CLIENT_TO_DELETE("id_client_to_delete"),
    ORDER("order"),
    DATE_IN("date_in"),
    DATE_OUT("date_out"),
    DATE_FROM_TO_SHOW_ORDERS("date_from_for_show_orders"),
    DATE_BEFORE_TO_SHOW_ORDERS("date_before_for_show_orders"),
    CLIENT_ID("client_id"),
    FOODPLAN("foodplan"),
    CLIENTS_TO_ADD_TO_ORDER("clients_to_add_to_order"),
    CLIENT_IDS_TO_ADD_TO_ORDER("client_ids_to_add_to_order"),
    ROOM_TYPE("room_type"),
    ROOM_SIZE("room_size"),
    ROOM_ID("room_id"),
    ORDER_ID_TO_SHOW_DETAIL("order_id_to_show_detail"),
    ORDER_ID("order_id"),
    SUCCESS("success"),
    ORDER_DETAIL("order_detail"),
    EMPTY_ROOMS("empty_rooms"),
    ROOM_SIZES("room_sizes"),
    ROOM_TYPES("room_types"),
    FOOD_PLANS("food_plans"),
    STATUSES("statuses"),
    RELATED_CLIENT_ID("related_client_id"),
    CLIENT_FOR_SHOW_RELATED_ORDERS("client_for_show_related_orders"),
    CLIENT_SEARCH_PATTERN("client_search_pattern"),
    NEW_SEARCH_CLIENT("new_search_client"),
    NEW_LIST("new_orders_list"),
    LAST_SHOW_ORDERS_COMMAND("last_show_orders_command"),
    ORDER_STATUS("order_status"),
    LOGIN_INCLUDE("login_include"),
    LAST_COMMAND_BEFORE_ORDERS_SHOW("last_command_before_orders_show"),
    ROOMS_ID("rooms_id");


    public final String var;

    private Vars(String var) {
        this.var = var;
    }
}
